export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import Header from "@/components/header"

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       <Header/>
          
        {children}
        <footer
        style={{backgroundColor:"green",padding:"1rem"}}
        >
          <p>footer</p>
        </footer>
      </body>
    </html>
  )
}
